 version: '2'
 services:
   reporting:
     image: registry.manadrdev.com/attendances-reporting
     depends_on:
       - mongo_db
   mongo_db:
      image: mongo
      volumes:
        - /datadrive/attendances/d1:/var/lib/mongodb
        - /datadrive/attendances/d2:/data/db